<a href="https://colab.research.google.com/github/jylee092/dataHW08/blob/main/04_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 자고싶어요
자고싶어요


In [2]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [3]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [4]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [5]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1][2]

3.14

In [7]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [8]:
arVal[0][2]

't'

In [9]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [10]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [11]:
arData.sum()

15.44

In [12]:
arVal.sum()

AttributeError: ignored

In [13]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arData.std()

1.4717934637713266

In [15]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [16]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [17]:
arData ** 2

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [18]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [19]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [20]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [21]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [22]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [24]:
import pandas as pd
pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [25]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [26]:
pandas_series[0]

30

In [27]:
pandas_series[0][1]

IndexError: ignored

In [28]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [29]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [30]:
df.columns

Index(['score'], dtype='object')

In [31]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [32]:
df.sum()

score    60
dtype: int64

In [33]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [34]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [35]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [36]:
del df['score']

In [37]:
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [38]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [39]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])
df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [40]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [41]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0 -0.604265 -0.809969 -2.220831  0.500578 -0.471495
1 -0.601268 -0.516578 -0.863159  0.332505  0.774581
2 -0.168843 -0.820715  0.861555  0.259346 -0.590867
3 -0.346562 -2.553758  0.900678 -0.094635 -0.183877
4  0.134478  0.024636  0.925075  0.051828 -1.456402

In [42]:
df.max()

A    0.134478
B    0.024636
C    0.925075
D    0.500578
E    0.774581
dtype: float64

In [43]:
df.min()

A   -0.604265
B   -2.553758
C   -2.220831
D   -0.094635
E   -1.456402
dtype: float64

In [44]:
df.mean()

A   -0.317292
B   -0.935277
C   -0.079336
D    0.209924
E   -0.385612
dtype: float64

In [45]:
df.std()

A    0.312244
B    0.967606
C    1.419060
D    0.234360
E    0.803561
dtype: float64

In [46]:
df.cumsum()

A         B         C         D         E
0 -0.604265 -0.809969 -2.220831  0.500578 -0.471495
1 -1.205533 -1.326546 -3.083990  0.833083  0.303086
2 -1.374377 -2.147261 -2.222435  1.092428 -0.287781
3 -1.720939 -4.701019 -1.321757  0.997794 -0.471658
4 -1.586461 -4.676383 -0.396682  1.049622 -1.928060

In [47]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -0.317292 -0.935277 -0.079336  0.209924 -0.385612
std    0.312244  0.967606  1.419060  0.234360  0.803561
min   -0.604265 -2.553758 -2.220831 -0.094635 -1.456402
25%   -0.601268 -0.820715 -0.863159  0.051828 -0.590867
50%   -0.346562 -0.809969  0.861555  0.259346 -0.471495
75%   -0.168843 -0.516578  0.900678  0.332505 -0.183877
max    0.134478  0.024636  0.925075  0.500578  0.774581

In [48]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.604265 -0.809969 -2.220831  0.500578 -0.471495        X
1 -0.601268 -0.516578 -0.863159  0.332505  0.774581        Y
2 -0.168843 -0.820715  0.861555  0.259346 -0.590867        X
3 -0.346562 -2.553758  0.900678 -0.094635 -0.183877        Y
4  0.134478  0.024636  0.925075  0.051828 -1.456402        Z

In [49]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.386554 -0.815342 -0.679638  0.379962 -0.531181
Y        -0.473915 -1.535168  0.018760  0.118935  0.295352
Z         0.134478  0.024636  0.925075  0.051828 -1.456402