In [1]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장


In [3]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [4]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [5]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [6]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [7]:
arVal[1][2]

3.14

In [8]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [9]:
arVal[0][2]

't'

In [10]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [11]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [12]:
arData.sum()

15.44

In [13]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [14]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
arData.std()

1.4717934637713266

In [16]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [17]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [18]:
arData ** 2

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [19]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [20]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [21]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [22]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [23]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [25]:
import pandas as pd
pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [26]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [27]:
pandas_series[0]

30

In [28]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [29]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [30]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [31]:
df.columns

Index(['score'], dtype='object')

In [32]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [33]:
df.sum()

score    60
dtype: int64

In [34]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [35]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [36]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [37]:
del df['score']

In [38]:
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [39]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [40]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])
df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [41]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [42]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']
df

A         B         C         D         E
0 -0.440062 -1.307636 -0.792222 -0.637998 -1.143994
1  0.669637  3.282333  1.752781  0.086123 -0.348486
2 -0.400681 -0.454079 -0.018023 -0.720368 -1.566113
3 -0.106185 -0.384366 -0.082670  1.826953  0.270759
4  0.718008 -0.265437  0.832259 -1.368657  0.094190

In [43]:
df.max()

A    0.718008
B    3.282333
C    1.752781
D    1.826953
E    0.270759
dtype: float64

In [44]:
df.min()

A   -0.440062
B   -1.307636
C   -0.792222
D   -1.368657
E   -1.566113
dtype: float64

In [45]:
df.mean()

A    0.088143
B    0.174163
C    0.338425
D   -0.162789
E   -0.538729
dtype: float64

In [46]:
df.std()

A    0.568018
B    1.785801
C    0.978138
D    1.225955
E    0.792767
dtype: float64

In [47]:
df.cumsum()

A         B         C         D         E
0 -0.440062 -1.307636 -0.792222 -0.637998 -1.143994
1  0.229575  1.974697  0.960559 -0.551876 -1.492480
2 -0.171107  1.520618  0.942536 -1.272243 -3.058594
3 -0.277291  1.136251  0.859866  0.554710 -2.787834
4  0.440716  0.870815  1.692126 -0.813947 -2.693644

In [48]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.088143  0.174163  0.338425 -0.162789 -0.538729
std    0.568018  1.785801  0.978138  1.225955  0.792767
min   -0.440062 -1.307636 -0.792222 -1.368657 -1.566113
25%   -0.400681 -0.454079 -0.082670 -0.720368 -1.143994
50%   -0.106185 -0.384366 -0.018023 -0.637998 -0.348486
75%    0.669637 -0.265437  0.832259  0.086123  0.094190
max    0.718008  3.282333  1.752781  1.826953  0.270759

In [49]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.440062 -1.307636 -0.792222 -0.637998 -1.143994        X
1  0.669637  3.282333  1.752781  0.086123 -0.348486        Y
2 -0.400681 -0.454079 -0.018023 -0.720368 -1.566113        X
3 -0.106185 -0.384366 -0.082670  1.826953  0.270759        Y
4  0.718008 -0.265437  0.832259 -1.368657  0.094190        Z

In [50]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.420372 -0.880858 -0.405123 -0.679183 -1.355054
Y         0.281726  1.448983  0.835056  0.956538 -0.038864
Z         0.718008 -0.265437  0.832259 -1.368657  0.094190